---
title: "First Knit"
author: "Anthony Falconio"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---


# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  Before I came to Antelope Valley College, I attended Lancaster High School. I personally graduated from high school in 2021. I find English to be an easier subject than Math, but I enjoy math more. I performed better in English overall. I just found that it came more naturally to me. I generally enjoyed my high school experience with both subjects.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I personally use a windows 10 computer as I have the most experience with the windows operating system. However, I do find apple computers to be more intuitive in my experience. I would consider myself as somewhat knowledgeable so about a 7 on the scale. I have more experience with computer hardware rather than software. My internet connection is very stable in my home for the most part. I think it's because I use an Ethernet cable to connect to the internet.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I've never gone by any name other than my regular, legal name which is Anthony. So in this case I just prefer to be called by "Anthony."   
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   Ideally, I would like to become an Aerospace Engineer in the long-term. This may or may not involve other achievements such as military experience depending on my financial situation, and if I need the help. My current major is Math for Transfer as I have learned to enjoy the subject, but I don't think it's the most interesting. I think physics is the most interesting subjects as it takes concepts learned in applied math classes and applies them to real world scenarios. When I originally graduated high school I had the plan of obtaining a bachelor's degree. I am now considering obtaining a master's degree if I continue to find myself more personally interested in my major.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have never been to a foreign country, but I would very much like to travel if I was given the opportunity. My favorite countries that I would like to visit would be Japan, Britain, France, Italy, Spain, Mexico, and El Salvador. I have never been in the military and I used to not think about in the past, but it might be the best choice for me to afford going to college in the long run. Most people in family have told me to join the Air Force as it best fits what I would want to do with my interest in Aerospace Engineering.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I have never taken Math 115 or Math 116 before. I did not know that Math 115 only satisfies the general education requirement, but Math 116 counts as a statistics class for other transfer institutions. My future plans are to ideally attend Cal Poly Pomona which I believe is a fairly competitive school to be admitted to so I will hopefully obtain an A grade in this class.
 






  




